# Generated by Django 5.1.1 on 2024-11-22 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_discount_applied'),
        ('profiles', '0003_loyaltypointstransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('not_received', 'Order Not Received'), ('damaged', 'Damaged Item(s)'), ('missing', 'Missing Item(s)'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='checkout.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_manage_issues', 'Can manage customer issues')],
            },
        ),
    ]
